name: Propagate changes to data projects

on: 
  push:
    branches:
      - data  # assuming changes are pushed to the `data` branch
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the originating project'
        required: true
        type: string

jobs:
  identify-and-print:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print project name
      run: |
        if [ "${{ github.event.inputs.project_name }}" == "project1" ]; then
          echo "Project: Project1"
        elif [ "${{ github.event.inputs.project_name }}" == "project2" ]; then
          echo "Project: Project2"
        elif [ "${{ github.event.inputs.project_name }}" == "project3" ]; then
          echo "Project: Project3"
        else
          echo "Unknown project: ${{ github.event.inputs.project_name }}"
        fi
